image: golang:1.12.7

variables:
  REPO_NAME: gitlab.worldiety.net/worldiety/customer/wdy/libriety/shopware/rackjobber

stages:
 - lint
 - build
 - release

before_script:
 - mkdir -p $GOPATH/src/$(dirname $REPO_NAME) $GOPATH/src/_/builds
 - cp -r $CI_PROJECT_DIR $GOPATH/src/gitlab.worldiety.net/worldiety/customer/wdy/libriety/shopware/rackjobber
 - ln -s $GOPATH/src/gitlab.worldiety.net/worldiety/customer/wdy/libriety/shopware/rackjobber /go/src/_/builds/rackjobber
 - make dep || true

lint:
 stage: lint
 script:
  - make setup
  - make lint

build:
 stage: build
 script:
  - make build

release:
  rules:
    - if: '$CI_COMMIT_TAG != ""'
  stage: release
  script: 
  - rm -rf .git
  - git init
  - git add .
  - git config --global user.email "info@worldiety.de"
  - git config --global user.name "worldiety"
  - git commit -m "release on Github"
  - git tag $CI_COMMIT_TAG 
  - git remote add github_release https://$GITHUB_USER:$GITHUB_PASS@github.com/worldiety/Rackjobber.git
  - git push --set-upstream github_release master --force
  - make installGoreleaser
  - make release