# This file was generated by GoReleaser. DO NOT EDIT.
class Rackjobber < Formula
  desc "CI-Tool for shopware plugin versioning"
  homepage "https://worldiety.de/"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/worldiety/rackjobber/releases/download/1.0.1/rackjobber_1.0.1_macOS_64-bit.tar.gz"
    sha256 "8afb5b278eb688a58ec477dce6a20d5a6f7bd78017320a3b259c1a5cd457371e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/worldiety/rackjobber/releases/download/1.0.1/rackjobber_1.0.1_Linux_64-bit.tar.gz"
      sha256 "9e178e646ff808554813fc345aa781353a5a0575dbe74d7be2e0b1683227c8a2"
    end
  end

  def install
    bin.install "rackjobber"
  end
end
